openapi: 3.0.0
info:
  title: MyProject API
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
paths:
  /news:
    get:
      summary: Получить новости
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /achievements:
    get:
      summary: Получить достижения
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /support:
    get:
      summary: Получить поддержку
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
