/**
 * MyProject API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 */

import ApiClient from "../ApiClient";
import NewsGet200Response from '../model/NewsGet200Response';

export default class DefaultApi {
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    achievementsGet(callback) {
        let postBody = null;
        let pathParams = {};
        let queryParams = {};
        let headerParams = {};
        let formParams = {};
        let authNames = [];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = NewsGet200Response;

        return this.apiClient.callApi(
            '/achievements', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
        );
    }

    getTableData(callback) {
        let postBody = null;
        let pathParams = {};
        let queryParams = {};
        let headerParams = {};
        let formParams = {};
        let authNames = [];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = [['String']];

        return this.apiClient.callApi(
            '/table-data', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
        );
    }

    newsGet(callback) {
        let postBody = null;
        let pathParams = {};
        let queryParams = {};
        let headerParams = {};
        let formParams = {};
        let authNames = [];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = NewsGet200Response;

        return this.apiClient.callApi(
            '/news', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
        );
    }

    supportGet(callback) {
        let postBody = null;
        let pathParams = {};
        let queryParams = {};
        let headerParams = {};
        let formParams = {};
        let authNames = [];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = NewsGet200Response;

        return this.apiClient.callApi(
            '/support', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
        );
    }

    updateTableCell(body, callback) {
        let postBody = body;

        if (body === undefined || body === null) {
            throw new Error("Missing the required parameter 'body' when calling updateTableCell");
        }

        let pathParams = {};
        let queryParams = {};
        let headerParams = {};
        let formParams = {};
        let authNames = [];
        let contentTypes = ['application/json'];
        let accepts = ['application/json'];
        let returnType = Object;

        return this.apiClient.callApi(
            '/table-data/cell', 'POST',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
        );
    }
}
