/**
 * MyProject API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import NewsGet200Response from '../model/NewsGet200Response';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the achievementsGet operation.
     * @callback module:api/DefaultApi~achievementsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/NewsGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получить достижения
     * @param {module:api/DefaultApi~achievementsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/NewsGet200Response}
     */
    achievementsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = NewsGet200Response;
      return this.apiClient.callApi(
        '/achievements', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the newsGet operation.
     * @callback module:api/DefaultApi~newsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/NewsGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получить новости
     * @param {module:api/DefaultApi~newsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/NewsGet200Response}
     */
    newsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = NewsGet200Response;
      return this.apiClient.callApi(
        '/news', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the supportGet operation.
     * @callback module:api/DefaultApi~supportGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/NewsGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получить поддержку
     * @param {module:api/DefaultApi~supportGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/NewsGet200Response}
     */
    supportGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = NewsGet200Response;
      return this.apiClient.callApi(
        '/support', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
