/**
 * MyProject API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import superagent from "superagent";

/**
* @module ApiClient
* @version 1.0.0
*/

/**
* Manages low level client-server communications, parameter marshalling, etc. There should not be any need for an
* application to use this class directly - the *Api and model classes provide the public API for the service. The
* contents of this file should be regarded as internal but are documented for completeness.
* @alias module:ApiClient
* @class
*/
class ApiClient {
    /**
     * The base URL against which to resolve every API call's (relative) path.
     * Overrides the default value set in spec file if present
     * @param {String} basePath
     */
    constructor(
        basePath =
            typeof window !== 'undefined'
                ? `${window.location.protocol}//${window.location.hostname}:5000/api`
                : 'http://localhost:5000/api'
    ) {
        /**
         * The base URL against which to resolve every API call's (relative) path.
         * @type {String}
         */
        this.basePath = basePath.replace(/\/+$/, '');

        /**
         * The authentication methods to be included for all API calls.
         * @type {Array.<String>}
         */
        this.authentications = {
        };

        /**
         * The default HTTP headers to be included for all API calls.
         * @type {Array.<String>}
         * @default {}
         */
        this.defaultHeaders = {
            'User-Agent': 'OpenAPI-Generator/1.0.0/Javascript'
        };

        /**
         * The default HTTP timeout for all API calls.
         * @type {Number}
         * @default 60000
         */
        this.timeout = 60000;

        /**
         * If set to false an additional timestamp parameter is added to all API GET calls to
         * prevent browser caching
         * @type {Boolean}
         * @default true
         */
        this.cache = true;

        /**
         * If set to true, the client will save the cookies from each server
         * response, and return them in the next request.
         * @default false
         */
        this.enableCookies = false;

        /*
         * Used to save and return cookies in a node.js (non-browser) setting,
         * if this.enableCookies is set to true.
         */
        if (typeof window === 'undefined') {
            this.agent = new superagent.agent();
        }

        /*
         * Allow user to override superagent agent
         */
        this.requestAgent = null;

        /*
         * Allow user to add superagent plugins
         */
        this.plugins = null;
    }

    /**
    * Returns a string representation for an actual parameter.
    * @param param The actual parameter.
    * @returns {String} The string representation of <code>param</code>.
    */
    paramToString(param) {
        if (param == undefined || param == null) {
            return '';
        }

        if (param instanceof Date) {
            return param.toJSON();
        }

        if (ApiClient.canBeJsonified(param)) {
            return JSON.stringify(param);
        }

        return param.toString();
    }

    /**
    * Returns a boolean indicating if the parameter could be JSON.stringified
    * @param param The actual parameter
    * @returns {Boolean} Flag indicating if <code>param</code> can be JSON.stringified
    */
    static canBeJsonified(str) {
        if (typeof str !== 'string' && typeof str !== 'object') {
            return false;
        }

        try {
            const type = str.toString();

            return type === '[object Object]' ||
                type === '[object Array]';
        } catch (err) {
            return false;
        }
    }

    /**
    * Builds full URL by appending the given path to the base URL and replacing path parameter place-holders with parameter values.
    * NOTE: query parameters are not handled here.
    * @param {String} path The path to append to the base URL.
    * @param {Object} pathParams The parameter values to append.
    * @param {String} apiBasePath Base path defined in the path, operation level to override the default one
    * @returns {String} The encoded path with parameter values substituted.
    */
    buildUrl(path, pathParams, apiBasePath) {
        if (!path.match(/^\//)) {
            path = '/' + path;
        }

        var url = this.basePath + path;

        // use API (operation, path) base path if defined
        if (apiBasePath !== null && apiBasePath !== undefined) {
            url = apiBasePath + path;
        }

        url = url.replace(/\{([\w-\.#]+)\}/g, (fullMatch, key) => {
            var value;

            if (pathParams.hasOwnProperty(key)) {
                value = this.paramToString(pathParams[key]);
            } else {
                value = fullMatch;
            }

            return encodeURIComponent(value);
        });

        return url;
    }

    /**
    * Checks whether the given content type represents JSON.<br>
    * JSON content type examples:<br>
    * <ul>
    * <li>application/json</li>
    * <li>application/json; charset=UTF8</li>
    * <li>APPLICATION/JSON</li>
    * </ul>
    * @param {String} contentType The MIME content type to check.
    * @returns {Boolean} <code>true</code> if <code>contentType</code> represents JSON, otherwise <code>false</code>.
    */
    isJsonMime(contentType) {
        return Boolean(
            contentType != null &&
            contentType.match(/^application\/json(;.*)?$/i)
        );
    }

    /**
    * Chooses a content type from the given array, with JSON preferred; i.e. return JSON if included, otherwise return the first.
    * @param {Array.<String>} contentTypes
    * @returns {String} The chosen content type, preferring JSON.
    */
    jsonPreferredMime(contentTypes) {
        for (var i = 0; i < contentTypes.length; i++) {
            if (this.isJsonMime(contentTypes[i])) {
                return contentTypes[i];
            }
        }

        return contentTypes[0];
    }

    /**
    * Checks whether the given parameter value represents file-like content.
    * @param param The parameter to check.
    * @returns {Boolean} <code>true</code> if <code>param</code> represents a file.
    */
    isFileParam(param) {
        if (typeof require === 'function') {
            let fs;

            try {
                fs = require('fs');
            } catch (err) {}

            if (fs && fs.ReadStream && param instanceof fs.ReadStream) {
                return true;
            }
        }

        if (typeof Buffer === 'function' && param instanceof Buffer) {
            return true;
        }

        if (typeof Blob === 'function' && param instanceof Blob) {
            return true;
        }

        if (typeof File === 'function' && param instanceof File) {
            return true;
        }

        return false;
    }

    /**
    * Normalizes parameter values.
    */
    normalizeParams(params) {
        var newParams = {};

        for (var key in params) {
            if (
                params.hasOwnProperty(key) &&
                params[key] != undefined &&
                params[key] != null
            ) {
                var value = params[key];

                if (this.isFileParam(value) || Array.isArray(value)) {
                    newParams[key] = value;
                } else {
                    newParams[key] = this.paramToString(value);
                }
            }
        }

        return newParams;
    }

    buildCollectionParam(param, collectionFormat) {
        if (param == null) {
            return null;
        }

        switch (collectionFormat) {
            case 'csv':
                return param.map(this.paramToString, this).join(',');

            case 'ssv':
                return param.map(this.paramToString, this).join(' ');

            case 'tsv':
                return param.map(this.paramToString, this).join('\t');

            case 'pipes':
                return param.map(this.paramToString, this).join('|');

            case 'multi':
                return param.map(this.paramToString, this);

            case 'passthrough':
                return param;

            default:
                throw new Error(
                    'Unknown collection format: ' + collectionFormat
                );
        }
    }

    applyAuthToRequest(request, authNames) {
        authNames.forEach((authName) => {
            var auth = this.authentications[authName];

            switch (auth.type) {
                case 'basic':
                    if (auth.username || auth.password) {
                        request.auth(
                            auth.username || '',
                            auth.password || ''
                        );
                    }
                    break;

                case 'bearer':
                    if (auth.accessToken) {
                        var localVarBearerToken =
                            typeof auth.accessToken === 'function'
                                ? auth.accessToken()
                                : auth.accessToken;

                        request.set({
                            'Authorization':
                                'Bearer ' + localVarBearerToken
                        });
                    }
                    break;

                case 'apiKey':
                    if (auth.apiKey) {
                        var data = {};

                        if (auth.apiKeyPrefix) {
                            data[auth.name] =
                                auth.apiKeyPrefix + ' ' + auth.apiKey;
                        } else {
                            data[auth.name] = auth.apiKey;
                        }

                        if (auth['in'] === 'header') {
                            request.set(data);
                        } else {
                            request.query(data);
                        }
                    }
                    break;

                case 'oauth2':
                    if (auth.accessToken) {
                        request.set({
                            'Authorization':
                                'Bearer ' + auth.accessToken
                        });
                    }
                    break;

                default:
                    throw new Error(
                        'Unknown authentication type: ' + auth.type
                    );
            }
        });
    }

    deserialize(response, returnType) {
        if (
            response == null ||
            returnType == null ||
            response.status == 204
        ) {
            return null;
        }

        var data = response.body;

        if (
            data == null ||
            (
                typeof data === 'object' &&
                typeof data.length === 'undefined' &&
                !Object.keys(data).length
            )
        ) {
            data = response.text;
        }

        return ApiClient.convertToType(data, returnType);
    }

    callApi(
        path,
        httpMethod,
        pathParams,
        queryParams,
        headerParams,
        formParams,
        bodyParam,
        authNames,
        contentTypes,
        accepts,
        returnType,
        apiBasePath,
        callback
    ) {
        var url = this.buildUrl(
            path,
            pathParams,
            apiBasePath
        );

        var request = superagent(httpMethod, url);

        if (this.plugins !== null) {
            for (var index in this.plugins) {
                if (this.plugins.hasOwnProperty(index)) {
                    request.use(this.plugins[index]);
                }
            }
        }

        this.applyAuthToRequest(request, authNames);

        if (
            httpMethod.toUpperCase() === 'GET' &&
            this.cache === false
        ) {
            queryParams['_'] = new Date().getTime();
        }

        request.query(
            this.normalizeParams(queryParams)
        );

        request
            .set(this.defaultHeaders)
            .set(this.normalizeParams(headerParams));

        if (this.requestAgent) {
            request.agent(this.requestAgent);
        }

        request.timeout(this.timeout);

        var contentType =
            this.jsonPreferredMime(contentTypes);

        if (contentType) {
            if (contentType != 'multipart/form-data') {
                request.type(contentType);
            }
        }

        if (
            contentType ===
            'application/x-www-form-urlencoded'
        ) {
            let normalizedParams =
                this.normalizeParams(formParams);

            let urlSearchParams =
                new URLSearchParams(normalizedParams);

            let queryString =
                urlSearchParams.toString();

            request.send(queryString);
        } else if (
            contentType == 'multipart/form-data'
        ) {
            var _formParams =
                this.normalizeParams(formParams);

            for (var key in _formParams) {
                if (_formParams.hasOwnProperty(key)) {
                    let _formParamsValue =
                        _formParams[key];

                    if (
                        this.isFileParam(
                            _formParamsValue
                        )
                    ) {
                        request.attach(
                            key,
                            _formParamsValue
                        );
                    } else if (
                        Array.isArray(
                            _formParamsValue
                        ) &&
                        _formParamsValue.length &&
                        this.isFileParam(
                            _formParamsValue[0]
                        )
                    ) {
                        _formParamsValue.forEach(
                            file =>
                                request.attach(
                                    key,
                                    file
                                )
                        );
                    } else {
                        request.field(
                            key,
                            _formParamsValue
                        );
                    }
                }
            }
        } else if (
            bodyParam !== null &&
            bodyParam !== undefined
        ) {
            if (!request.header['Content-Type']) {
                request.type('application/json');
            }

            request.send(bodyParam);
        }

        var accept =
            this.jsonPreferredMime(accepts);

        if (accept) {
            request.accept(accept);
        }

        if (returnType === 'Blob') {
            request.responseType('blob');
        } else if (returnType === 'String') {
            request.responseType('text');
        }

        if (this.enableCookies) {
            if (typeof window === 'undefined') {
                this.agent._attachCookies(request);
            } else {
                request.withCredentials();
            }
        }

        request.end((error, response) => {
            if (callback) {
                var data = null;

                if (!error) {
                    try {
                        data = this.deserialize(
                            response,
                            returnType
                        );

                        if (
                            this.enableCookies &&
                            typeof window === 'undefined'
                        ) {
                            this.agent._saveCookies(
                                response
                            );
                        }
                    } catch (err) {
                        error = err;
                    }
                }

                callback(
                    error,
                    data,
                    response
                );
            }
        });

        return request;
    }

    static parseDate(str) {
        if (isNaN(str)) {
            return new Date(
                str.replace(
                    /(\d)(T)(\d)/i,
                    '$1 $3'
                )
            );
        }

        return new Date(+str);
    }

    static convertToType(data, type) {
        if (
            data === null ||
            data === undefined
        ) {
            return data;
        }

        switch (type) {
            case 'Boolean':
                return Boolean(data);

            case 'Integer':
                return parseInt(data, 10);

            case 'Number':
                return parseFloat(data);

            case 'String':
                return String(data);

            case 'Date':
                return ApiClient.parseDate(
                    String(data)
                );

            case 'Blob':
                return data;

            default:
                if (type === Object) {
                    return data;
                } else if (
                    typeof type.constructFromObject ===
                    'function'
                ) {
                    return type.constructFromObject(
                        data
                    );
                } else if (Array.isArray(type)) {
                    var itemType = type[0];

                    return data.map((item) => {
                        return ApiClient.convertToType(
                            item,
                            itemType
                        );
                    });
                } else if (
                    typeof type === 'object'
                ) {
                    var keyType;
                    var valueType;

                    for (var k in type) {
                        if (type.hasOwnProperty(k)) {
                            keyType = k;
                            valueType = type[k];
                            break;
                        }
                    }

                    var result = {};

                    for (var key in data) {
                        if (
                            data.hasOwnProperty(key)
                        ) {
                            var convertedKey =
                                ApiClient.convertToType(
                                    key,
                                    keyType
                                );

                            var convertedValue =
                                ApiClient.convertToType(
                                    data[key],
                                    valueType
                                );

                            result[convertedKey] =
                                convertedValue;
                        }
                    }

                    return result;
                }

                return data;
        }
    }

    /**
    * Gets an array of host settings
    * @returns An array of host settings
    */
    hostSettings() {
        const url =
            typeof window !== 'undefined'
                ? `${window.location.protocol}//${window.location.hostname}:5000/api`
                : 'http://localhost:5000/api';

        return [
            {
                'url': url,
                'description':
                    'No description provided'
            }
        ];
    }

    getBasePathFromSettings(
        index,
        variables = {}
    ) {
        var servers = this.hostSettings();

        if (
            index < 0 ||
            index >= servers.length
        ) {
            throw new Error(
                'Invalid index ' +
                index +
                ' when selecting the host settings. Must be less than ' +
                servers.length
            );
        }

        var server = servers[index];
        var url = server['url'];

        for (
            var variable_name in
            server['variables']
        ) {
            if (
                variable_name in variables
            ) {
                let variable =
                    server['variables'][
                        variable_name
                    ];

                if (
                    !(
                        'enum_values' in
                        variable
                    ) ||
                    variable[
                        'enum_values'
                    ].includes(
                        variables[
                            variable_name
                        ]
                    )
                ) {
                    url = url.replace(
                        '{' +
                        variable_name +
                        '}',
                        variables[
                            variable_name
                        ]
                    );
                } else {
                    throw new Error(
                        'The variable `' +
                        variable_name +
                        '` in the host URL has invalid value ' +
                        variables[
                            variable_name
                        ] +
                        '. Must be ' +
                        server['variables'][
                            variable_name
                        ][
                            'enum_values'
                        ] +
                        '.'
                    );
                }
            } else {
                url = url.replace(
                    '{' +
                    variable_name +
                    '}',
                    server['variables'][
                        variable_name
                    ]['default_value']
                );
            }
        }

        return url;
    }

    static constructFromObject(
        data,
        obj,
        itemType
    ) {
        if (Array.isArray(data)) {
            for (
                var i = 0;
                i < data.length;
                i++
            ) {
                if (data.hasOwnProperty(i)) {
                    obj[i] =
                        ApiClient.convertToType(
                            data[i],
                            itemType
                        );
                }
            }
        } else {
            for (var k in data) {
                if (data.hasOwnProperty(k)) {
                    obj[k] =
                        data[k];
                }
            }
        }
    }
}

ApiClient.CollectionFormatEnum = {
    CSV: ',',
    SSV: ' ',
    TSV: '\t',
    PIPES: '|',
    MULTI: 'multi'
};

ApiClient.instance = new ApiClient();

if (typeof window !== 'undefined') {
    delete ApiClient.instance.defaultHeaders[
        'User-Agent'
    ];
}

export default ApiClient;